=== TimPaterson/TouchscreenDigitalReadout/bin/ScreenDesigner.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- definition of attributes -->
  <xs:attribute name="Name" type="xs:string"/>
  <xs:attribute name="RefName" type="xs:string"/>
  <xs:attribute name="Fill" type="xs:string"/>
  <xs:attribute name="Location" type="xs:string"/>
  <xs:attribute name="Height" type="xs:string"/>
  <xs:attribute name="Width" type="xs:string"/>
  <xs:attribute name="RowHeight" type="xs:string"/>
  <xs:attribute name="ColumnWidth" type="xs:string"/>
  <xs:attribute name="StrokeThickness" type="xs:string"/>
  <xs:attribute name="Stroke" type="xs:string"/>
  <xs:attribute name="Top" type="xs:string"/>
  <xs:attribute name="Left" type="xs:string"/>
  <xs:attribute name="Group" type="xs:string"/>
  <xs:attribute name="ColorDepth" type="BitsPerPixel"/>
  <xs:attribute name="ShowValue" type="xs:string"/>
  <xs:attribute name="StrideMultiple" type="Multiple"/>
  <xs:attribute name="WidthMultiple" type="Multiple"/>

  <xs:attributeGroup name="Element">
    <xs:attribute ref="Name"/>
    <xs:attribute ref="Top" />
    <xs:attribute ref="Left" />
    <xs:attribute ref="Location" />
  </xs:attributeGroup>

  <xs:attributeGroup name="AreaGroup">
    <xs:attribute name="Area" type="xs:string"/>
    <xs:attribute name="Group" type="xs:string"/>
    <xs:attribute name="HotSpot" type="xs:string" />
  </xs:attributeGroup>

  <xs:attributeGroup name="FontGroup">
    <xs:attribute name="FontFamily" type="xs:string" />
    <xs:attribute name="FontWeight" type="FontWeights" />
    <xs:attribute name="FontStyle" type="FontStyles" />
    <xs:attribute name="FontStretch" type="FontStretches" />
    <xs:attribute name="FontSize" type="xs:string" />
    <xs:attribute name="Font" type="xs:string" />
  </xs:attributeGroup>

  <xs:simpleType name="BitsPerPixel">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Color8bpp" />
      <xs:enumeration value="Color16bpp" />
      <xs:enumeration value="Color24bpp" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Multiple">
    <xs:restriction base="xs:integer">
      <xs:enumeration value="1" />
      <xs:enumeration value="2" />
      <xs:enumeration value="4" />
      <xs:enumeration value="8" />
      <xs:enumeration value="16" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="FontStretches">
    <xs:restriction base="xs:string">
      <xs:enumeration value="UltraCondensed" />
      <xs:enumeration value="ExtraCondensed" />
      <xs:enumeration value="Condensed" />
      <xs:enumeration value="SemiCondensed" />
      <xs:enumeration value="Normal" />
      <xs:enumeration value="Medium" />
      <xs:enumeration value="SemiExpanded" />
      <xs:enumeration value="Expanded" />
      <xs:enumeration value="ExtraExpanded" />
      <xs:enumeration value="UltraExpanded" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="FontWeights">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Thin" />
      <xs:enumeration value="ExtraLight" />
      <xs:enumeration value="UltraLight" />
      <xs:enumeration value="Light" />
      <xs:enumeration value="Normal" />
      <xs:enumeration value="Regular" />
      <xs:enumeration value="Medium" />
      <xs:enumeration value="DemiBold" />
      <xs:enumeration value="SemiBold" />
      <xs:enumeration value="Bold" />
      <xs:enumeration value="ExtraBold" />
      <xs:enumeration value="UltraBold" />
      <xs:enumeration value="Black" />
      <xs:enumeration value="Heavy" />
      <xs:enumeration value="ExtraBlack" />
      <xs:enumeration value="UltraBlack" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="FontStyles">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Italic" />
      <xs:enumeration value="Normal" />
      <xs:enumeration value="Oblique" />
    </xs:restriction>
  </xs:simpleType>

  <!-- definition of complex elements -->
  <xs:complexType name="TopContent_t">
    <xs:choice maxOccurs="unbounded">
      <xs:element ref="Grid" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="Rectangle" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="Ellipse" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="Line" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="TextBlock" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="Image" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="Set" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="SetString" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="Font" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="Color" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="Ref" minOccurs="0" maxOccurs="unbounded" />
    </xs:choice>
  </xs:complexType>

  <xs:element name="Project">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element ref="Canvas" maxOccurs="unbounded" />
        <xs:element ref="Component" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="Set" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="SetString" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="Font" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="Color" minOccurs="0" maxOccurs="unbounded" />
      </xs:choice>
      <xs:attribute ref="StrideMultiple"/>
      <xs:attribute ref="WidthMultiple"/>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Component_t">
    <xs:complexContent>
      <xs:extension base="TopContent_t">
        <xs:attribute ref="Name" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="Component" type="Component_t" />

  <xs:complexType name="Canvas_t">
    <xs:complexContent>
      <xs:extension base="TopContent_t">
        <xs:sequence>
          <xs:element ref="Item" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute ref="Name" use="required"/>
        <xs:attribute ref="Height" use="required"/>
        <xs:attribute ref="Width"/>
        <xs:attribute ref="StrideMultiple"/>
        <xs:attribute ref="WidthMultiple"/>
        <xs:attribute ref="Fill" use="required"/>
        <xs:attribute ref="ColorDepth" use="required"/>
        <xs:attribute name="Type" type="xs:string"/>
        <xs:attribute name="ItemWidth" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="Item" type="Content_t" />
  
  <xs:element name="Canvas" type="Canvas_t" />

  <xs:complexType name="Content_t">
    <xs:complexContent>
      <xs:extension base="TopContent_t">
        <xs:attributeGroup ref="Element" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Rectangle_t">
    <xs:complexContent>
      <xs:extension base="Content_t">
        <xs:attributeGroup ref="AreaGroup" />
        <xs:attribute ref="Height" use="required" />
        <xs:attribute ref="Width" use="required" />
        <xs:attribute ref="StrokeThickness" />
        <xs:attribute ref="Stroke" />
        <xs:attribute ref="Fill" />
        <xs:attribute name="RadiusX" type="xs:string" />
        <xs:attribute name="RadiusY" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="Rectangle" type="Rectangle_t" />

  <xs:complexType name="Ellipse_t">
    <xs:complexContent>
      <xs:extension base="Content_t">
        <xs:attributeGroup ref="AreaGroup" />
        <xs:attribute ref="Height" use="required" />
        <xs:attribute ref="Width" use="required" />
        <xs:attribute ref="StrokeThickness" />
        <xs:attribute ref="Stroke" />
        <xs:attribute ref="Fill" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="Ellipse" type="Ellipse_t" />

  <xs:complexType name="Line_t">
    <xs:complexContent>
      <xs:extension base="Content_t">
        <xs:attribute name="X1" type="xs:string" use="required" />
        <xs:attribute name="Y1" type="xs:string" use="required" />
        <xs:attribute name="X2" type="xs:string" use="required" />
        <xs:attribute name="Y2" type="xs:string" use="required" />
        <xs:attribute ref="Height" />
        <xs:attribute ref="Width" />
        <xs:attribute ref="StrokeThickness" />
        <xs:attribute ref="Stroke" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="Line" type="Line_t" />

  <xs:element name="TextBlock">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attributeGroup ref="Element" />
          <xs:attributeGroup ref="AreaGroup" />
          <xs:attributeGroup ref="FontGroup" />
          <xs:attribute ref="Height" />
          <xs:attribute ref="Width" />
          <xs:attribute name="Text" type="xs:string" />
          <xs:attribute name="Background" type="xs:string" />
          <xs:attribute name="Foreground" type="xs:string" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Image">
    <xs:complexType>
      <xs:attributeGroup ref="Element" />
      <xs:attributeGroup ref="AreaGroup" />
      <xs:attribute name="Source" type="xs:string" use="required" />
      <xs:attribute ref="Height" />
      <xs:attribute ref="Width" />
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Set_t">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute ref="ShowValue"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:element name="Set" type="Set_t" />

  <xs:element name="SetString" type="Set_t" />

  <xs:element name="Font">
    <xs:complexType>
      <xs:attribute ref="Name" use="required"/>
      <xs:attributeGroup ref="FontGroup" />
    </xs:complexType>
  </xs:element>

  <xs:element name="Color">
    <xs:complexType>
      <xs:attribute ref="Name" use="required"/>
      <xs:attribute name="Color" use="required"/>
      <xs:attribute ref="ColorDepth"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Grid">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Default" minOccurs="0" />
        <xs:element ref="Row" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attributeGroup ref="Element" />
      <xs:attribute ref="RowHeight" use="required" />
      <xs:attribute ref="ColumnWidth" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="Row">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Default" minOccurs="0" />
        <xs:choice minOccurs="1" maxOccurs="unbounded">
          <xs:element ref="Column" minOccurs="0" maxOccurs="unbounded" />
          <xs:element ref="ColumnNoDefault" minOccurs="0" maxOccurs="unbounded" />
        </xs:choice>
      </xs:sequence>
      <xs:attributeGroup ref="Element" />
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Column" type="Content_t" />
  
  <xs:element name="ColumnNoDefault" type="Content_t" />
  
  <xs:element name="Default" type="Content_t" />
  
  <xs:element name="Ref">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element ref="Set" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="SetString" minOccurs="0" maxOccurs="unbounded" />
      </xs:choice>
      <xs:attributeGroup ref="Element" />
      <xs:attribute ref="RefName" use="required"/>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== TimPaterson/TouchscreenDigitalReadout/Dro/Images/Screen.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Project [<!ENTITY Fonts SYSTEM "../Fonts/Fonts.xml">]>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="http://www.timpaterson.com/schemas/ScreenDesigner.xsd"
         StrideMultiple="4">
  &Fonts;
  <Set>
    ScreenHeight = 600;
    ScreenWidth = 1024;
  	BtnHeight = 60;
  	BtnWidth = 60;
  	KeySpace = 10;
  	BtnFontSize = BtnHeight * 3 / 4;
  	SmallTextHeight = CalcSmall_Height;

    <!-- ListScroll parameters -->
    ScrollGapLeft = 2;
    ScrollGapRight = 2;
    ScrollThumbWidth = 50;
    ScrollThumbHeight = BtnHeight;
    ScrollBarWidth = ScrollGapLeft + ScrollThumbWidth + ScrollGapRight;
  </Set>
  <Set ShowValue="ScrollGapLeft">ScrollGapLeft</Set>
  <Set ShowValue="ScrollGapRight">ScrollGapRight</Set>
  <Set ShowValue="ScrollThumbWidth">ScrollThumbWidth</Set>
  <Set ShowValue="ScrollThumbHeight">ScrollThumbHeight</Set>
  <Set ShowValue="ScrollBarWidth">ScrollBarWidth</Set>
  <Font Name="BtnFont" FontSize="BtnFontSize" FontFamily="Arial"/>
  <Font Name="BtnSmallFont" FontSize="BtnFontSize * 3 / 4" />
  <Color Name="ScreenForeColor" Color="Black" ColorDepth="Color16bpp"/>
  <Color Name="ScreenBackColor" Color="0xC0FFFF" ColorDepth="Color16bpp"/>
  <Color Name="AxisForeColor" Color="Black" />
  <Color Name="AxisBackColor" Color="Yellow" />
  <Color Name="CalcBackColor" Color="White" />
  <Color Name="MemColorOdd" Color="0xFFE8E8" ColorDepth="Color16bpp"/>
  <Color Name="MemColorEven" Color="0xD0FFD0" ColorDepth="Color16bpp"/>
  <Color Name="BtnBackground" Color="0x606060"/>
  <Color Name="ToolDiagramColor" Color="DarkSlateGray" ColorDepth="Color16bpp"/>
  <Color Name="FeedRateColor" Color="White" ColorDepth="Color16bpp"/>
  <Color Name="ToolInfoBackground" Color="Blue" ColorDepth="Color16bpp"/>
  <Color Name="ToolInfoForeground" Color="White" ColorDepth="Color16bpp"/>
  <Color Name="ToolLibBackground" Color="DarkBlue" ColorDepth="Color16bpp"/>
  <Color Name="ToolLibForeground" Color="LightGray" ColorDepth="Color16bpp"/>
  <Color Name="ToolLibSelected" Color="White" ColorDepth="Color16bpp"/>
  <Color Name="TimeEntryForeground" Color="Black" ColorDepth="Color16bpp"/>
  <Color Name="TimeEntryBackground" Color="White" ColorDepth="Color16bpp"/>
  <Color Name="ScrollBarColor" Color="0x303030" ColorDepth="Color16bpp"/>
  <Color Name="UndoTextColor" Color="Gray" ColorDepth="Color16bpp"/>
  <Color Name="UndoLineColor" Color="Blue" ColorDepth="Color16bpp"/>
  <Color Name="UndoBackColor" Color="CalcBackColor" ColorDepth="Color16bpp"/>

  <!-- Components -->
  <Component Name="Key">
    <Rectangle Name="Button" Height="BtnHeight" Width="BtnWidth"
      RadiusX="8" RadiusY="8" StrokeThickness="0" Fill="White">
      <TextBlock Name="Label" Font="BtnFont" Foreground="Black"/>
    </Rectangle>
  </Component>

  <Component Name="Memory">
    <Rectangle Name="MemRect" Group="Memory" Height="BtnHeight" Width="150">
      <Rectangle Name="MemDisp" Top="BtnHeight / 4" Left="10" Height="BtnHeight / 2" Width="140"/>
    </Rectangle>
  </Component>

  <Component Name="Toggle">
    <Color Name="ToggleOn" Color="Yellow"/>
    <Rectangle Name="Button" Height="BtnHeight" Width="BtnWidth"
      RadiusX="8" RadiusY="8" StrokeThickness="0" Fill="BtnBackground">
      <TextBlock Name="Upper" FontSize="BtnFontSize / 2" Top="1" Foreground="DarkGray" FontFamily="Arial" Text="abs" />
      <Line X1="10" Y1="BtnHeight / 2" X2="BtnWidth - 10" Y2="BtnHeight / 2" Stroke="White" StrokeThickness="2" />
      <TextBlock Name="Lower" FontSize="BtnFontSize / 2" Top="33" Foreground="DarkGray" FontFamily="Arial" Text="inc" />
    </Rectangle>
  </Component>

  <Component Name="InchMetric">
    <Ref RefName="Toggle"/>
    <Set>
      Upper.Text = "inch";
    	Lower.Text = "mm";
    </Set>
  </Component>

  <Set>
    <!-- Axis displays -->
    DispHt = DigitDisplay_Height;
    DispWd = 410;
    DigHt = 96;
    LabHt = 72;
    Vspace = 25;
    LabTop = (DispHt - DigHt) / 2;
    AxisBtnWidth = 85;
    AxisBtnGap = 25;
    AxisBtnLeft = DispWd + AxisBtnGap;
    AxisBtnRight = AxisBtnLeft + AxisBtnWidth;

    <!-- Caculator displays -->
    KeypadWidth = KeySpace + (BtnWidth + KeySpace) * 4;
    KeypadRight = ScreenWidth - (BtnWidth * 2 + KeySpace * 3);
    KeypadLeft = KeypadRight - KeypadWidth;
    KeypadHeight = KeySpace + (BtnHeight + KeySpace) * 5;
    CalcTextHeight = BtnHeight;
    UndoTop = Vspace;
    UndoItemHeight = SmallTextHeight;
    UndoHeight = UndoItemHeight * 3;
    CalcDispTop = UndoTop + UndoHeight + KeySpace;
    CalcTextTop = CalcDispTop + CalcTextHeight + KeySpace;
    KeypadTop = CalcTextTop + SmallTextHeight + KeySpace;
    KeypadBottom = KeypadTop + KeypadHeight;

    <!-- Undo lists -->
    UndoLeft = AxisBtnRight + AxisBtnGap;
    UndoRight = KeypadRight;
    UndoWidth = UndoRight - UndoLeft;
    UndoItemWidth = (UndoWidth - 2) / 3;
    UndoVertSep1Left = UndoItemWidth;
    UndoVertSep2Left = UndoItemWidth * 2 + 1;

    <!-- Tool display column widths & positions -->
    ToolNumWidth = 54;
    ToolDiamWidth = 70;
    ToolFluteWidth = 55;
    ToolLengthWidth = 85;

    ToolNumLeft = 0;
    ToolDiamLeft = ToolNumLeft + ToolNumWidth;
    ToolFluteLeft = ToolDiamLeft + ToolDiamWidth;
    ToolLengthLeft = ToolFluteLeft + ToolFluteWidth;
    ToolDescLeft = ToolLengthLeft + ToolLengthWidth;

    ToolTextHeight = SmallTextHeight;
    ToolTextNumLeft = ToolNumWidth - 3 * 14 - 4;

    <!-- Tool Library -->
    ToolLibHeight = CalcDispTop - 2;
    ToolLibWidth = ScreenWidth;
    ToolLibLeft = KeySpace;
    ToolListHeight = ScreenHeight - ToolLibHeight;
    ToolListWidth = KeypadLeft - 8;
    ToolRowWidth = ToolListWidth - ScrollBarWidth;

    <!-- Controls -->
    ToolBtnHeight = BtnHeight;
    ToolBtnWidth = BtnWidth;
    ClearBtnWidth = 50;
    ClearBtnHeight = 50;
    EditBoxMargin = 5;
    ToolCtrlHeight = ToolLibHeight - KeySpace;
    ToolButtonsWidth = ToolBtnWidth * 3 + KeySpace * 2;
    ToolButtonsLeft = ToolLibWidth - ToolButtonsWidth - KeySpace;

    <!-- ToolButtonsLeft & ToolInfoClearBtnLeft relative left edge, other relative ToolLibLeft -->
    ToolInfoClearBtnLeft = ToolButtonsLeft - KeySpace - ClearBtnWidth - 1;
    ToolInfoDescWidth = ToolButtonsLeft - ToolLibLeft - KeySpace - ToolDescLeft; <!-- the whole box -->
    ToolInfoTextWidth = ToolInfoClearBtnLeft - ToolLibLeft - ToolDescLeft - 2 * EditBoxMargin; <!-- text editing area -->
    ToolListDescWidth = ToolRowWidth - ToolLibLeft - ToolDescLeft;
    ToolDescTextLeft = EditBoxMargin;

    ToolInfoHeight = 60;
    ToolLabelHeight = ToolLibHeight - ToolInfoHeight - KeySpace;
    ToolInfoClearBtnTop = (ToolInfoHeight - ClearBtnHeight) / 2 + KeySpace;
    ToolRowHeight = 50;
  </Set>

  <!-- Tool label line -->
  <Component Name="ToolLabel">
    <Rectangle Name="Item" Height="40" Width="ToolNumWidth" StrokeThickness="1" Stroke="ToolInfoForeground">
      <TextBlock Name="Label" Font="CalcSmall" Foreground="ToolInfoForeground"/>
    </Rectangle>
  </Component>

  <Component Name="ToolLabels">
    <Ref RefName="ToolLabel" Left="ToolNumLeft">
      <Set>
        Item.Width = ToolNumWidth + 1;
        Label.Text = Tool;
      </Set>
    </Ref>
    <Ref RefName="ToolLabel" Left="ToolDiamLeft">
      <Set>
        Item.Width = ToolDiamWidth + 1;
        Label.Text = Dia.;
      </Set>
    </Ref>
    <Ref RefName="ToolLabel" Left="ToolFluteLeft">
      <Set>
        Item.Width = ToolFluteWidth + 1;
        Label.Text = Flut.;
      </Set>
    </Ref>
    <Ref RefName="ToolLabel" Left="ToolLengthLeft">
      <Set>
        Item.Width = ToolLengthWidth + 1;
        Label.Text = Length;
      </Set>
    </Ref>
    <Ref RefName="ToolLabel" Left="ToolDescLeft">
      <Set>
        Label.Text = Description;
        Item.Name = ToolLabelDesc;
        Label.Name = ToolTextDesc;
      </Set>
    </Ref>
  </Component>

  <!-- Tool info line -->
  <Component Name="ToolItem">
    <Rectangle Name="Item" Height="ToolInfoHeight + 1" Width="ToolNumWidth" StrokeThickness="1" Stroke="ToolInfoForeground">
      <Rectangle Name="Spot" Group="ToolLib" Height="ToolInfoHeight + 1" Width="ToolNumWidth"/>
      <Rectangle Name="TextAreaTop" Height="ToolTextHeight" Width="ToolNumWidth">
        <Rectangle Name="TextArea" Height="ToolTextHeight" Width="ToolNumWidth">
          <TextBlock Name="DummyText" Left="0" Top="0" Font="CalcSmall"/>
        </Rectangle>
      </Rectangle>
    </Rectangle>
  </Component>

  <Component Name="ToolInfo">
    <Ref RefName="ToolItem" Left="ToolNumLeft">
      <Set>
        Item.Width = ToolNumWidth + 1;
        Spot.Width = ToolNumWidth + 1;
        Spot.HotSpot = ToolNumber;
        TextArea.Left = ToolTextNumLeft;
        TextArea.Width = ToolNumWidth - ToolTextNumLeft - 1;
        TextArea.Area = ToolNumber;
        TextArea.Name = ToolNumber;
        DummyText.Text = 100;
      </Set>
    </Ref>
    <Ref RefName="ToolItem" Left="ToolDiamLeft">
      <Set>
        Item.Width = ToolDiamWidth + 1;
        Spot.Width = ToolDiamWidth + 1;
        Spot.HotSpot = ToolDiameter;
        TextArea.Left = 5;
        TextArea.Width = ToolDiamWidth - 6;
        TextArea.Area = ToolDiameter;
        TextArea.Name = ToolDiameter;
        DummyText.Text = 0.375;
      </Set>
    </Ref>
    <Ref RefName="ToolItem" Left="ToolFluteLeft">
      <Set>
        Item.Width = ToolFluteWidth + 1;
        Spot.Width = ToolFluteWidth + 1;
        Spot.HotSpot = ToolFlutes;
        TextArea.Left = 9;
        TextArea.Width = ToolFluteWidth - 10;
        TextArea.Area = ToolFlutes;
        TextArea.Name = ToolFlutes;
        DummyText.Text = 003;
      </Set>
    </Ref>
    <Ref RefName="ToolItem" Left="ToolLengthLeft">
      <Set>
        Item.Width = ToolLengthWidth + 1;
        Spot.Width = ToolLengthWidth + 1;
        Spot.HotSpot = ToolLength;
        TextArea.Left = 6;
        TextArea.Width = ToolLengthWidth - 7;
        TextArea.Area = ToolLength;
        TextArea.Name = ToolLength;
